# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_streaming.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'audio_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61udio_streaming.proto\x12\x0f\x61udio_streaming\"!\n\nAudioChunk\x12\x13\n\x0b\x61udio_chunk\x18\x01 \x01(\x0c\"%\n\x15TranscriptionResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"#\n\x0c\x41udioRequest\x12\x13\n\x0b\x61udio_chunk\x18\x01 \x01(\x0c\x32m\n\x14TranscriptionService\x12U\n\nTranscribe\x12\x1b.audio_streaming.AudioChunk\x1a&.audio_streaming.TranscriptionResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=42
  _globals['_AUDIOCHUNK']._serialized_end=75
  _globals['_TRANSCRIPTIONRESPONSE']._serialized_start=77
  _globals['_TRANSCRIPTIONRESPONSE']._serialized_end=114
  _globals['_AUDIOREQUEST']._serialized_start=116
  _globals['_AUDIOREQUEST']._serialized_end=151
  _globals['_TRANSCRIPTIONSERVICE']._serialized_start=153
  _globals['_TRANSCRIPTIONSERVICE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
